### PR TITLE
Add non string map keys

### PR DESCRIPTION
**Pull request by rdblue**
Support non-string keys in maps (#3).

### CODE REVIEW

**Comment by rdblue** [comment]
FYI @omalley.

**Comment by omalley** [comment]
Looks good. It was a much larger patch than I was expecting.

I usually squash commits like this as I commit them to master to make the history easier to read.

**Comment by rdblue** [comment]
Most of the reason for the additional size was that this moved Avro reads and writes over to ValueReader and ValueWriter like Spark uses. That made it easier to support the map logical type and also made reading and writing those maps more efficient because logical types deserialize to generic classes and then convert. The ValueReader approach can go directly to/from map and an Avro array. The downside was restructuring the Spark and Avro code so much to make it happen.

I debated squashing, but I thought it would be better to have separate commits since as a whole the changes were so large.

**Comment by rdblue** [comment]
Forgot to mention: another bonus is that scanning manifest files seems to be ~10-20% faster.

**Pull request merged**
