### PR TITLE
Update Spark to 2.4.0

### LINKED ISSUE #94: Upgrade to Spark 2.4.0
Spark 2.4.0 was just released. We should upgrade iceberg-spark's Spark dependency to latest.

### PR DESCRIPTION
**Pull request by rdblue**
This updates the Spark dependency to 2.4.0.

Changes include:
* Remove ORC support that uses a now-private Spark API (BufferHolder)
* Use Spark filters instead of expressions, which are no longer used in the v2 API

This fixes #94.

### CODE REVIEW

**Comment by rdblue** [comment]
FYI @omalley: Spark 2.4 broke ORC support, so we either need to fix it or remove it from Spark in the master branch. What would you prefer to do?

**Comment by rdblue** [comment]
@charleso, we want to support multiple versions of Spark at the same time, but right now the API that we're using to integrate is evolving rapidly. It just doesn't make sense right now to support them all. Eventually, we will either use reflection or have versioned Spark modules.

**Comment by charleso** [comment]
@rdblue Thanks for that, exactly what I wanted to know. 👍

**Comment by rdblue** [comment]
Closing this. The new one is https://github.com/apache/incubator-iceberg/pull/30.

**Pull request closed without merging**
